title: Angela Zhang
logo: /assets/img/face.png
theme: jekyll-theme-minimal
description: 

  UW Comp Sci '24, Passion 2 Purpose '19, CWSF '18, QCSYS '18, \n SHAD Western '17, DECA ICDC '16 & '18

favicon:
  source: favicon.ico
  path: /_layouts
