title: Angela Zhang
logo: /assets/img/ski.jpg
theme: jekyll-theme-minimal
description: 

  change
  UW CS '24, P2P '19, CWSF '18, QCSYS '17, SHAD '17, ICDC '16 & '18
  'email: angelazhangyr@gmail.com'


resume: here
linkedin: here
behance: here
devpost: here
medium: here
plugins: 
  - jekyll-seo-tag