title: Angela Zhang
logo: /assets/img/face.jpg
theme: jekyll-theme-minimal
description: 

  \n changedUW Comp Sci '24, Passion 2 Purpose '19, CWSF '18, QCSYS '18, SHAD Western '17, DECA ICDC '16 & '18

plugins: 
  - jekyll-seo-tag