title: Angela Zhang
logo: /assets/img/ski.jpg
theme: jekyll-theme-minimal
description: 
  UW CS '24, P2P '19, CWSF '18, QCSYS '18, SHAD '17, DECA ICDC '16 & '18
  'email: angelazhangyr@gmail.com'
resume: here
linkedin: here
behance: here
devpost: here
medium: here
plugins: 
  - jekyll-seo-tag